#!/bin/sh

# customizable settings
export VBOX_ROOT="${VBOX_ROOT:-${HOME}/vm}"
export VBOX_DISK_SIZE=${VBOX_DISK_SIZE:-25000}
export VBOX_MEM=${VBOX_MEM:-8192}
export VBOX_N_CPU=${VBOX_N_CPU:-4}
export VBOX_SCANCODE_LIMIT=${VBOX_SCANCODE_LIMIT:-24}
