# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

# using the most generic optimisation settings.
CFLAGS="-O2 -pipe -mtune=generic -fomit-frame-pointer"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

USE="-X -cups -gtk -qt5 aspell dbus ibm icu ipv6 spell truetype udev vim-syntax xen"

# if the target VM is distributed, keep the following commented to avoid
# legal issues.
# USE="${USE} -bindist"

# Using standard /var locations introduced in 2019
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# ensure buildpkg if this is a build provider
# FEATURES="${FEATURES} buildpkg"
# Appending getbinpkg to the list of values within the FEATURES variable
FEATURES="${FEATURES} getbinpkg"
# Require signatures
FEATURES="${FEATURES} binpkg-request-signature"

# set mirror to the closest geographical location to this vm's host
GENTOO_MIRRORS="{GENTOO_MIRROR}"

# Apache settings
APACHE2_MPMS="prefork"
APACHE2_MODULES="${APACHE2_MODULES} access_compat proxy proxy_http"

# there is no value in forcing the guest to boot in uefi, so remove that
# as a dependency unless it is required (fill in/comment as necessary)
GRUB_PLATFORMS="pc"
